from pathlib import Path

categories = [
    ("API", "API", ["descoberta de endpoints", "métodos HTTP", "parâmetros", "respostas", "erros", "documentação exposta", "rotas administrativas", "rotas de debug", "versionamento", "paginação", "filtros", "CORS da API", "content negotiation", "status codes", "limites de tamanho", "timeouts", "redirecionamentos", "cache da API", "formatos de erro", "telemetria"]),
    ("Authentication", "AUTH", ["login", "política de senha", "sessão", "JWT", "tokens", "expiração", "recuperação de senha", "MFA", "proteção contra brute force", "rate limiting", "logout", "reautenticação", "remember me", "troca de senha", "enumeração de usuários", "credenciais padrão", "cookies de autenticação", "CSRF em autenticação", "login social", "bloqueio de conta"]),
    ("Authorization", "AUTHZ", ["IDOR", "acesso horizontal", "acesso vertical", "recursos sem autorização", "endpoints administrativos", "elevação de privilégio", "escopos", "roles", "permissões herdadas", "objetos excluídos", "multi-tenancy", "mass assignment", "funções internas", "exportações", "ações destrutivas", "webhooks protegidos", "jobs protegidos", "arquivos privados", "rotas internas", "fallback de autorização"]),
    ("Secrets", "SECRET", ["API keys", "tokens", "passwords", "chaves privadas", "credenciais", "arquivos .env", "configurações", "segredos em commits", "segredos em logs", "segredos em assets", "cloud credentials", "certificados", "webhooks", "DSNs", "senhas de banco", "chaves de sessão", "segredos de CI", "segredos em exemplos", "entropia de tokens", "redação de evidências"]),
    ("Headers", "HEADER", ["CSP", "HSTS", "X-Content-Type-Options", "X-Frame-Options", "Referrer-Policy", "Permissions-Policy", "COOP", "COEP", "CORP", "Cache-Control", "headers de servidor", "headers de debug", "content type", "content disposition", "cookies Secure", "cookies HttpOnly", "SameSite", "origem", "política de embed", "proteção de MIME"]),
    ("CORS", "CORS", ["origens permitidas", "wildcard", "credenciais", "preflight", "métodos", "headers", "origem nula", "subdomínios", "reflexão de origem", "cache de preflight", "exposição de headers", "origens de desenvolvimento", "origens internas", "WebSocket origin", "origens em erro", "política por rota", "regex de origem", "protocolo inseguro", "porta de origem", "documentação CORS"]),
    ("Input", "INPUT", ["validação", "sanitização", "XSS", "SQL injection", "command injection", "template injection", "path traversal", "LDAP injection", "NoSQL injection", "header injection", "CRLF", "open redirect", "prototype pollution", "deserialização", "regex DoS", "upload de arquivo", "MIME spoofing", "encoding", "tamanho de entrada", "caracteres de controle"]),
    ("Files", "FILE", ["uploads", "extensões", "MIME", "path traversal", "arquivos sensíveis", "temporários", "backups", "listagem de diretórios", "permissões", "symlinks", "nomes de arquivo", "arquivos ocultos", "source maps", "logs", "artefatos de build", "downloads", "preview de arquivos", "cache local", "arquivos públicos", "isolamento de workspace"]),
    ("Dependencies", "DEP", ["dependências diretas", "dependências transitivas", "lockfiles", "versões vulneráveis", "pacotes abandonados", "scripts de instalação", "dependências de desenvolvimento", "licenças", "integridade", "fontes de pacotes", "pacotes privados", "typosquatting", "duplicidade", "atualizações", "runtime", "SDKs", "imagens base", "plugins", "bibliotecas nativas", "reprodutibilidade"]),
    ("Configuration", "CONFIG", ["modo debug", "stack traces", "ambiente", "credenciais", "portas", "serviços expostos", "flags inseguras", "defaults", "logging", "monitoramento", "feature flags", "configuração remota", "segredos de deploy", "TLS", "proxy", "timeouts", "retry", "limites", "permissões", "configuração de produção"]),
    ("Exposure", "EXPOSE", ["PII", "tokens", "dados internos", "mensagens de erro", "arquivos públicos", "metadados", "informações de versão", "rotas de saúde", "backups públicos", "índices", "logs públicos", "relatórios", "respostas verbose", "identificadores", "dados de debug", "endereços internos", "nomes de usuários", "e-mails", "telemetria", "cache compartilhado"]),
    ("Resilience", "RES", ["timeout", "retry", "circuit breaker", "falha de dependência", "indisponibilidade", "fallback", "idempotência", "concorrência", "fila", "dead letter", "cancelamento", "graceful shutdown", "limite de memória", "limite de CPU", "backpressure", "reconexão", "transação", "consistência", "degradação", "recuperação"]),
    ("Stress", "STRESS", ["carga controlada", "concorrência", "rate limit", "estabilidade", "tempo de resposta", "recuperação após carga", "burst", "fila sob carga", "limite por usuário", "limite por IP", "payload grande", "conexões", "workers", "pool de banco", "cache sob carga", "latência", "erro sob carga", "shutdown sob carga", "isolamento", "limite global"]),
    ("Web", "WEB", ["cookies", "sessões", "CSRF", "clickjacking", "mixed content", "TLS", "redirecionamento", "cache", "service worker", "manifest", "storage", "postMessage", "origins", "iframes", "CSP de assets", "integridade SRI", "links externos", "formulários", "métodos inseguros", "navegador legado"]),
    ("Supply Chain", "CHAIN", ["proveniência", "SBOM", "assinaturas", "build reproduzível", "CI", "artefatos", "release", "dependabot", "branch protection", "segredos CI", "permissões de workflow", "actions de terceiros", "runners", "cache de CI", "tags", "releases", "imagens", "changelog", "revisão de código", "política de contribuição"]),
]

out = '''/** Registro determinístico de verificações do Security Test Lab.\n * Cada entrada aponta para um executor adversarial dentro do target autorizado.\n */\nexport type TestSeverity = "critical" | "high" | "medium" | "low" | "info";\nexport type SecurityTest = { id: string; name: string; category: string; severity: TestSeverity; description: string; active: true; approach: "adversarial"; executor: "scoped-probe"; guardrails: string[] };\n\n'''
out += 'const definitions = [\n'
for name, code, items in categories:
    out += f'  {{ name: "{name}", code: "{code}", items: {items!r} }},\n'
out += '] as const;\n\n'
out += '''export const TEST_REGISTRY: SecurityTest[] = definitions.flatMap((category) =>\n  category.items.map((item, index) => ({\n    id: `SEC-${category.code}-${String(index + 1).padStart(3, "0")}`,\n    name: `Verificar ${item}`,\n    category: category.name,\n    severity: index < 2 ? "high" : index < 7 ? "medium" : "low",\n    description: `Verificação determinística de ${item} no escopo autorizado.`,\n    active: true,
    approach: "adversarial",
    executor: "scoped-probe",
    guardrails: ["scope-guard", "timeout", "request-budget", "synthetic-only", "redacted-evidence"],\n  }))\n);\n\nexport const TEST_CATEGORIES = definitions.map(({ name, code }) => ({\n  name,\n  code,\n  count: TEST_REGISTRY.filter((test) => test.category === name).length,\n}));\n\nif (TEST_REGISTRY.length !== 300) {\n  throw new Error(`Expected 300 security tests, got ${TEST_REGISTRY.length}`);\n}\n'''
Path('/home/ubuntu/security-test-lab/lib/test-registry.ts').write_text(out)
print(f'generated {sum(len(items) for _, _, items in categories)} tests across {len(categories)} categories')
